/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#d7e4f1',
        'inverse-primary': '#9ccaff',
        'surface-container-low': '#f1f4f6',
        'inverse-on-surface': '#eef1f3',
        'on-primary': '#ffffff',
        secondary: '#53606b',
        'surface-bright': '#f7fafc',
        error: '#ba1a1a',
        'on-primary-fixed': '#001d35',
        'on-tertiary-fixed': '#251a07',
        'primary-container': '#005288',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        outline: '#727780',
        'on-primary-container': '#91c5ff',
        'inverse-surface': '#2d3133',
        'surface-container': '#ebeef0',
        'on-secondary-fixed': '#101d26',
        surface: '#f7fafc',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'surface-dim': '#d7dadc',
        'on-primary-fixed-variant': '#00497b',
        primary: '#003a63',
        'secondary-fixed-dim': '#bbc8d5',
        'error-container': '#ffdad6',
        'on-secondary-container': '#596671',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#3c4852',
        'surface-container-high': '#e5e9eb',
        'on-surface-variant': '#41474f',
        'on-background': '#181c1e',
        'surface-container-highest': '#e0e3e5',
        'outline-variant': '#c1c7d1',
        'tertiary-fixed': '#f6dfc0',
        'on-surface': '#181c1e',
        'on-error': '#ffffff',
        'surface-tint': '#206298',
        tertiary: '#443621',
        'primary-fixed': '#d0e4ff',
        'tertiary-fixed-dim': '#d9c4a5',
        'secondary-container': '#d7e4f1',
        'primary-fixed-dim': '#9ccaff',
        'on-tertiary-fixed-variant': '#53452e',
        'on-tertiary-container': '#d3bea1',
        background: '#f7fafc',
        'tertiary-container': '#5c4d36',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
